[package]
name = "parser"
version = "0.1.0"
authors = ["Jason Orendorff <jason.orendorff@gmail.com>"]
edition = "2018"

[dependencies]
generated_parser = { path = "../generated_parser" }
ast = { path = "../ast" }
bumpalo = "2.6.0"
unic-ucd-ident = "0.9.0"
