[package]
name = "interpreter"
version = "0.1.0"
authors = ["Tom Schuster <evilpies@gmail.com>"]
edition = "2018"

[dependencies]
emitter = { path = "../emitter" }

[dev-dependencies]
ast = { path = "../ast" }
parser = { path = "../parser" }
bumpalo = "2.6.0"
